spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personfilter?autoReconnect=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456 # 自行修改一下密码
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 1 # 最小空闲连接数
      maximum-pool-size: 15 # 最大连接数量
      pool-name: user-pool
      connection-test-query: SELECT 1 # 测试连接
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update